require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MovetypesController do

  # This should return the minimal set of attributes required to create a valid
  # Movetype. As you add validations to Movetype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "movetype_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MovetypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all movetypes as @movetypes" do
      movetype = Movetype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:movetypes).should eq([movetype])
    end
  end

  describe "GET show" do
    it "assigns the requested movetype as @movetype" do
      movetype = Movetype.create! valid_attributes
      get :show, {:id => movetype.to_param}, valid_session
      assigns(:movetype).should eq(movetype)
    end
  end

  describe "GET new" do
    it "assigns a new movetype as @movetype" do
      get :new, {}, valid_session
      assigns(:movetype).should be_a_new(Movetype)
    end
  end

  describe "GET edit" do
    it "assigns the requested movetype as @movetype" do
      movetype = Movetype.create! valid_attributes
      get :edit, {:id => movetype.to_param}, valid_session
      assigns(:movetype).should eq(movetype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Movetype" do
        expect {
          post :create, {:movetype => valid_attributes}, valid_session
        }.to change(Movetype, :count).by(1)
      end

      it "assigns a newly created movetype as @movetype" do
        post :create, {:movetype => valid_attributes}, valid_session
        assigns(:movetype).should be_a(Movetype)
        assigns(:movetype).should be_persisted
      end

      it "redirects to the created movetype" do
        post :create, {:movetype => valid_attributes}, valid_session
        response.should redirect_to(Movetype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved movetype as @movetype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Movetype.any_instance.stub(:save).and_return(false)
        post :create, {:movetype => { "movetype_id" => "invalid value" }}, valid_session
        assigns(:movetype).should be_a_new(Movetype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Movetype.any_instance.stub(:save).and_return(false)
        post :create, {:movetype => { "movetype_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested movetype" do
        movetype = Movetype.create! valid_attributes
        # Assuming there are no other movetypes in the database, this
        # specifies that the Movetype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Movetype.any_instance.should_receive(:update).with({ "movetype_id" => "1" })
        put :update, {:id => movetype.to_param, :movetype => { "movetype_id" => "1" }}, valid_session
      end

      it "assigns the requested movetype as @movetype" do
        movetype = Movetype.create! valid_attributes
        put :update, {:id => movetype.to_param, :movetype => valid_attributes}, valid_session
        assigns(:movetype).should eq(movetype)
      end

      it "redirects to the movetype" do
        movetype = Movetype.create! valid_attributes
        put :update, {:id => movetype.to_param, :movetype => valid_attributes}, valid_session
        response.should redirect_to(movetype)
      end
    end

    describe "with invalid params" do
      it "assigns the movetype as @movetype" do
        movetype = Movetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Movetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => movetype.to_param, :movetype => { "movetype_id" => "invalid value" }}, valid_session
        assigns(:movetype).should eq(movetype)
      end

      it "re-renders the 'edit' template" do
        movetype = Movetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Movetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => movetype.to_param, :movetype => { "movetype_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested movetype" do
      movetype = Movetype.create! valid_attributes
      expect {
        delete :destroy, {:id => movetype.to_param}, valid_session
      }.to change(Movetype, :count).by(-1)
    end

    it "redirects to the movetypes list" do
      movetype = Movetype.create! valid_attributes
      delete :destroy, {:id => movetype.to_param}, valid_session
      response.should redirect_to(movetypes_url)
    end
  end

end
